import { Serie } from "./serie.js";
export var dataSeries = [
    new Serie(1, "Breaking Bad", 5, "AMC", "Set and filmed in Albuquerque, New Mexico, the series tells the story \n    of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "\"https://www.amc.com/shows/breaking-bad1", "https://i.imgur.com/GGje0vc.jpg"),
    new Serie(2, "Orange Is the New Black", 6, "Netflix", "The series begins revolving around Piper Chapman, a woman in her thirties living in \n    New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311", "https://i.imgur.com/EvKe48G.jpg"),
    new Serie(3, "Game of Thrones", 7, "HBO", "American fantasy drama", "https://www.hbo.com/game-of-thrones", "https://i.imgur.com/TDCEV1S.jpg"),
    new Serie(4, "The Big Bang Theory", 12, "CBS", "Leonard and Sheldon are brilliant physicists\u2014geniuses in the laboratory but socially challenged everywhere else. \n  Enter beautiful, street-smart neighbor Penny, who aims to teach them a thing or two about life. Despite their on-again, off-again relationship in the past, \n  Leonard and Penny have finally gotten married. Even Sheldon has found a female companion, entering into a relationship agreement with neurobiologist Amy Farrah Fowler, \n  and he recently took their relationship to the next level by marrying her after a long courtship. In their free time, \n  Leonard and Sheldon enjoy fantasy role-playing games with their ever-expanding universe of friends, including fellow \n  scientists Koothrappali, Wolowitz, and Wolowitz\u2019s adorable microbiologist wife, Bernadette, who is adjusting to life \n  with their two children.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://i.imgur.com/uAEpVWk.jpg"),
    new Serie(5, "Sherlock", 4, "BBC", "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) \n  solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend, Dr John Watson \n  (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps", "'https'://www.bbc.co.uk/programmes/b018ttws", "https://i.imgur.com/02B7qhj.jpg"),
    new Serie(6, "A Very English Scandal", 2, "BBC", "A Very English Scandal is a fact-based three-part British television \n  comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4", "https://i.imgur.com/D4y3DrQ.jpg"),
];
